// milo/ui/src/analysis/components/lit_associated_bugs_badge/tooltip.ts
// Copyright 2022 The LUCI Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import '@material/mwc-menu';
import { MobxLitElement } from '@adobe/lit-mobx';
import { css, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { makeObservable, observable } from 'mobx';

import { makeRuleLink } from '@/analysis/tools/utils';
import { Cluster } from '@/common/services/luci_analysis';
import { commonStyles } from '@/common/styles/stylesheets';

@customElement('milo-associated-bugs-tooltip')
export class AssociatedBugsTooltipElement extends MobxLitElement {
  @observable.ref project!: string;
  @observable.ref clusters!: readonly Cluster[];

  constructor() {
    super();
    makeObservable(this);
  }

  protected render() {
    const bugClusters = this.clusters.filter((c) => c.bug);

    return html`
      <table style="padding: 5px;">
        <tbody>
          <tr>
            <td colspan="2">
              This failure is associated with the following bug(s):
            </td>
          </tr>
          ${bugClusters.map(
            (c) => html`
              <tr class="row">
                <td><a href=${c.bug!.url}>${c.bug!.linkText}</a></td>
                <td>
                  <a
                    href=${makeRuleLink(this.project, c.clusterId.id)}
                    target="_blank"
                  >
                    Failures
                  </a>
                </td>
              </tr>
            `,
          )}
        </tbody>
      </table>
    `;
  }

  static styles = [
    commonStyles,
    css`
      :host {
        display: block;
        width: 300px;
      }

      table {
        width: 100%;
      }

      tr > td:first-child {
        width: 100%;
      }
    `,
  ];
}

// milo/ui/src/common/components/timestamp/tooltip.tsx
// Copyright 2024 The LUCI Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { DateTime } from 'luxon';

import { displayDuration } from '@/common/tools/time_utils';

import { TimeZoneConfig } from './constants';

export interface TooltipProps {
  readonly datetime: DateTime;
  readonly format: string;
  readonly zones: readonly TimeZoneConfig[];
}

export function Tooltip({ datetime, format, zones }: TooltipProps) {
  const now = DateTime.now();
  return (
    <table>
      <tbody>
        <tr>
          <td colSpan={2}>{displayDuration(now.diff(datetime))} ago</td>
        </tr>
        {zones.map((tz, i) => (
          <tr key={i}>
            <td>{tz.label}:</td>
            <td>{datetime.setZone(tz.zone).toFormat(format)}</td>
            <td>{now.setZone(tz.zone).toFormat(format)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
